var annotated_dup =
[
    [ "ArgosLib", "namespace_argos_lib.html", [
      [ "VibrationStatus", "struct_argos_lib_1_1_vibration_status.html", "struct_argos_lib_1_1_vibration_status" ],
      [ "XboxController", "class_argos_lib_1_1_xbox_controller.html", "class_argos_lib_1_1_xbox_controller" ]
    ] ],
    [ "motorConfig", "namespacemotor_config.html", [
      [ "drive", "namespacemotor_config_1_1drive.html", [
        [ "frontLeftDrive", "structmotor_config_1_1drive_1_1front_left_drive.html", "structmotor_config_1_1drive_1_1front_left_drive" ],
        [ "frontRightDrive", "structmotor_config_1_1drive_1_1front_right_drive.html", "structmotor_config_1_1drive_1_1front_right_drive" ],
        [ "rearRightDrive", "structmotor_config_1_1drive_1_1rear_right_drive.html", "structmotor_config_1_1drive_1_1rear_right_drive" ],
        [ "rearLeftDrive", "structmotor_config_1_1drive_1_1rear_left_drive.html", "structmotor_config_1_1drive_1_1rear_left_drive" ],
        [ "frontLeftTurn", "structmotor_config_1_1drive_1_1front_left_turn.html", "structmotor_config_1_1drive_1_1front_left_turn" ],
        [ "frontRightTurn", "structmotor_config_1_1drive_1_1front_right_turn.html", "structmotor_config_1_1drive_1_1front_right_turn" ],
        [ "rearRightTurn", "structmotor_config_1_1drive_1_1rear_right_turn.html", "structmotor_config_1_1drive_1_1rear_right_turn" ],
        [ "rearLeftTurn", "structmotor_config_1_1drive_1_1rear_left_turn.html", "structmotor_config_1_1drive_1_1rear_left_turn" ]
      ] ],
      [ "intake", "namespacemotor_config_1_1intake.html", [
        [ "intakeMotor", "structmotor_config_1_1intake_1_1intake_motor.html", "structmotor_config_1_1intake_1_1intake_motor" ]
      ] ]
    ] ],
    [ "sensorConfig", "namespacesensor_config.html", [
      [ "drive", "namespacesensor_config_1_1drive.html", [
        [ "frontLeftTurn", "structsensor_config_1_1drive_1_1front_left_turn.html", "structsensor_config_1_1drive_1_1front_left_turn" ],
        [ "frontRightTurn", "structsensor_config_1_1drive_1_1front_right_turn.html", "structsensor_config_1_1drive_1_1front_right_turn" ],
        [ "rearRightTurn", "structsensor_config_1_1drive_1_1rear_right_turn.html", "structsensor_config_1_1drive_1_1rear_right_turn" ],
        [ "rearLeftTurn", "structsensor_config_1_1drive_1_1rear_left_turn.html", "structsensor_config_1_1drive_1_1rear_left_turn" ]
      ] ]
    ] ],
    [ "debounceSetttings", "structdebounce_setttings.html", "structdebounce_setttings" ],
    [ "DriveSubsystem", "class_drive_subsystem.html", "class_drive_subsystem" ],
    [ "ExampleCommand", "class_example_command.html", "class_example_command" ],
    [ "ExampleSubsystem", "class_example_subsystem.html", "class_example_subsystem" ],
    [ "has_direction", "structhas__direction.html", null ],
    [ "has_direction< T, decltype((void) T::direction, void())>", "structhas__direction_3_01_t_00_01decltype_07_07void_08_01_t_1_1direction_00_01void_07_08_08_4.html", null ],
    [ "has_forwardLimit_deviceID", "structhas__forward_limit__device_i_d.html", null ],
    [ "has_forwardLimit_deviceID< T, decltype((void) T::forwardLimit_deviceID, void())>", "structhas__forward_limit__device_i_d_3_01_t_00_01decltype_07_07void_08_01_t_1_1forward_limit__device_i_d_00_01void_07_08_08_4.html", null ],
    [ "has_forwardLimit_normalState", "structhas__forward_limit__normal_state.html", null ],
    [ "has_forwardLimit_normalState< T, decltype((void) T::forwardLimit_normalState, void())>", "structhas__forward_limit__normal_state_3_01_t_00_01decltype_07_07void_08_01_t_1_1forward_limit__39f5ce3bc8ea108dbe2b011b12961a5c.html", null ],
    [ "has_forwardLimit_source", "structhas__forward_limit__source.html", null ],
    [ "has_forwardLimit_source< T, decltype((void) T::forwardLimit_source, void())>", "structhas__forward_limit__source_3_01_t_00_01decltype_07_07void_08_01_t_1_1forward_limit__source_00_01void_07_08_08_4.html", null ],
    [ "has_initMode", "structhas__init_mode.html", null ],
    [ "has_initMode< T, decltype((void) T::initMode, void())>", "structhas__init_mode_3_01_t_00_01decltype_07_07void_08_01_t_1_1init_mode_00_01void_07_08_08_4.html", null ],
    [ "has_inverted", "structhas__inverted.html", null ],
    [ "has_inverted< T, decltype((void) T::inverted, void())>", "structhas__inverted_3_01_t_00_01decltype_07_07void_08_01_t_1_1inverted_00_01void_07_08_08_4.html", null ],
    [ "has_magOffset", "structhas__mag_offset.html", null ],
    [ "has_magOffset< T, decltype((void) T::magOffset, void())>", "structhas__mag_offset_3_01_t_00_01decltype_07_07void_08_01_t_1_1mag_offset_00_01void_07_08_08_4.html", null ],
    [ "has_neutralDeadband", "structhas__neutral_deadband.html", null ],
    [ "has_neutralDeadband< T, decltype((void) T::neutralDeadband, void())>", "structhas__neutral_deadband_3_01_t_00_01decltype_07_07void_08_01_t_1_1neutral_deadband_00_01void_07_08_08_4.html", null ],
    [ "has_neutralMode", "structhas__neutral_mode.html", null ],
    [ "has_neutralMode< T, decltype((void) T::neutralMode, void())>", "structhas__neutral_mode_3_01_t_00_01decltype_07_07void_08_01_t_1_1neutral_mode_00_01void_07_08_08_4.html", null ],
    [ "has_pid0_allowableError", "structhas__pid0__allowable_error.html", null ],
    [ "has_pid0_allowableError< T, decltype((void) T::pid0_allowableError, void())>", "structhas__pid0__allowable_error_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__allowable_error_00_01void_07_08_08_4.html", null ],
    [ "has_pid0_iZone", "structhas__pid0__i_zone.html", null ],
    [ "has_pid0_iZone< T, decltype((void) T::pid0_iZone, void())>", "structhas__pid0__i_zone_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__i_zone_00_01void_07_08_08_4.html", null ],
    [ "has_pid0_kD", "structhas__pid0__k_d.html", null ],
    [ "has_pid0_kD< T, decltype((void) T::pid0_kD, void())>", "structhas__pid0__k_d_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_d_00_01void_07_08_08_4.html", null ],
    [ "has_pid0_kF", "structhas__pid0__k_f.html", null ],
    [ "has_pid0_kF< T, decltype((void) T::pid0_kF, void())>", "structhas__pid0__k_f_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_f_00_01void_07_08_08_4.html", null ],
    [ "has_pid0_kI", "structhas__pid0__k_i.html", null ],
    [ "has_pid0_kI< T, decltype((void) T::pid0_kI, void())>", "structhas__pid0__k_i_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_i_00_01void_07_08_08_4.html", null ],
    [ "has_pid0_kP", "structhas__pid0__k_p.html", null ],
    [ "has_pid0_kP< T, decltype((void) T::pid0_kP, void())>", "structhas__pid0__k_p_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_p_00_01void_07_08_08_4.html", null ],
    [ "has_pid0_selectedSensor", "structhas__pid0__selected_sensor.html", null ],
    [ "has_pid0_selectedSensor< T, decltype((void) T::pid0_selectedSensor, void())>", "structhas__pid0__selected_sensor_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__selected_sensor_00_01void_07_08_08_4.html", null ],
    [ "has_range", "structhas__range.html", null ],
    [ "has_range< T, decltype((void) T::range, void())>", "structhas__range_3_01_t_00_01decltype_07_07void_08_01_t_1_1range_00_01void_07_08_08_4.html", null ],
    [ "has_remoteFilter0_addr", "structhas__remote_filter0__addr.html", null ],
    [ "has_remoteFilter0_addr< T, decltype((void) T::remoteFilter0_addr, void())>", "structhas__remote_filter0__addr_3_01_t_00_01decltype_07_07void_08_01_t_1_1remote_filter0__addr_00_01void_07_08_08_4.html", null ],
    [ "has_remoteFilter0_type", "structhas__remote_filter0__type.html", null ],
    [ "has_remoteFilter0_type< T, decltype((void) T::remoteFilter0_type, void())>", "structhas__remote_filter0__type_3_01_t_00_01decltype_07_07void_08_01_t_1_1remote_filter0__type_00_01void_07_08_08_4.html", null ],
    [ "has_reverseLimit_deviceID", "structhas__reverse_limit__device_i_d.html", null ],
    [ "has_reverseLimit_deviceID< T, decltype((void) T::reverseLimit_deviceID, void())>", "structhas__reverse_limit__device_i_d_3_01_t_00_01decltype_07_07void_08_01_t_1_1reverse_limit__device_i_d_00_01void_07_08_08_4.html", null ],
    [ "has_reverseLimit_normalState", "structhas__reverse_limit__normal_state.html", null ],
    [ "has_reverseLimit_normalState< T, decltype((void) T::reverseLimit_normalState, void())>", "structhas__reverse_limit__normal_state_3_01_t_00_01decltype_07_07void_08_01_t_1_1reverse_limit__76fae7e8d68d384fb2201ee67d3ab1aa.html", null ],
    [ "has_reverseLimit_source", "structhas__reverse_limit__source.html", null ],
    [ "has_reverseLimit_source< T, decltype((void) T::reverseLimit_source, void())>", "structhas__reverse_limit__source_3_01_t_00_01decltype_07_07void_08_01_t_1_1reverse_limit__source_00_01void_07_08_08_4.html", null ],
    [ "has_sensorPhase", "structhas__sensor_phase.html", null ],
    [ "has_sensorPhase< T, decltype((void) T::sensorPhase, void())>", "structhas__sensor_phase_3_01_t_00_01decltype_07_07void_08_01_t_1_1sensor_phase_00_01void_07_08_08_4.html", null ],
    [ "has_supplyCurrentLimit", "structhas__supply_current_limit.html", null ],
    [ "has_supplyCurrentLimit< T, decltype((void) T::supplyCurrentLimit, void())>", "structhas__supply_current_limit_3_01_t_00_01decltype_07_07void_08_01_t_1_1supply_current_limit_00_01void_07_08_08_4.html", null ],
    [ "has_supplyCurrentThreshold", "structhas__supply_current_threshold.html", null ],
    [ "has_supplyCurrentThreshold< T, decltype((void) T::supplyCurrentThreshold, void())>", "structhas__supply_current_threshold_3_01_t_00_01decltype_07_07void_08_01_t_1_1supply_current_threshold_00_01void_07_08_08_4.html", null ],
    [ "has_supplyCurrentThresholdTime", "structhas__supply_current_threshold_time.html", null ],
    [ "has_supplyCurrentThresholdTime< T, decltype((void) T::supplyCurrentThresholdTime, void())>", "structhas__supply_current_threshold_time_3_01_t_00_01decltype_07_07void_08_01_t_1_1supply_curren3fa30c8ecaf7482aa3292ba7a023b768.html", null ],
    [ "has_voltCompSat", "structhas__volt_comp_sat.html", null ],
    [ "has_voltCompSat< T, decltype((void) T::voltCompSat, void())>", "structhas__volt_comp_sat_3_01_t_00_01decltype_07_07void_08_01_t_1_1volt_comp_sat_00_01void_07_08_08_4.html", null ],
    [ "IntakeSubsystem", "class_intake_subsystem.html", "class_intake_subsystem" ],
    [ "interpMapPoint", "structinterp_map_point.html", "structinterp_map_point" ],
    [ "interpolationMap", "classinterpolation_map.html", "classinterpolation_map" ],
    [ "Robot", "class_robot.html", "class_robot" ],
    [ "RobotContainer", "class_robot_container.html", "class_robot_container" ],
    [ "SwapControllersCommand", "class_swap_controllers_command.html", "class_swap_controllers_command" ],
    [ "SwappableControllersSubsystem", "class_swappable_controllers_subsystem.html", "class_swappable_controllers_subsystem" ]
];