# This is a basic workflow to build robot code.

name: Format

# Controls when the action will run. Triggers the workflow on push or pull request
on: [ push, pull_request]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "docs/**"]'
          do_not_skip: '["pull_request"]'
  wpiformat:
    name: "wpiformat"
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install clang-format
        run: sudo apt-get update -q && sudo apt-get install -y clang-format-10
      - name: Install wpiformat
        run: pip3 install wpiformat
      - name: Run
        run: wpiformat -clang 10
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: ${{ steps.git-check.outputs.modified == 'true' && !(github.event_name == 'push' && github.ref == 'refs/heads/master') }}
        uses: EndBug/add-and-commit@v7
        with:
          author_name: wpiformat
          message: Automated formatting changes
      - name: Create pull request
        if: ${{ steps.git-check.outputs.modified == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated formatting changes
          committer: GitHub <noreply@github.com>
          author: wpiformat <${{ github.actor }}@users.noreply.github.com>
          title: Formatting Changes
